server:
  port: 8081
  servlet:
    context-path: /springboot-leesite-demo
spring:
  application:
    name: springboot-leesite-demo

  profiles:
    active: test

  # druid DATABASE CONFIG https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE
  datasource:
    druid:
      #监控统计拦截的filters
      filters: stat
      #配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 100


#mybatis
mybatis-plus:
  # xml
  mapper-locations: classpath*:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.meiko.leesite.demo.domain
  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查
  check-config-location: true


logback:
  appName: demo
  fileType: log